name: flaskr

on: [push]

#on: 
#  pull_request:
#    branches:
#      - master
#  push: 
#    branches:
#      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Building flaskr application
      run: |
        docker build . -t flaskr
        docker run -d --rm --name flaskr-server flaskr
#    - name: wemake-python-styleguide
#      uses: wemake-services/wemake-python-styleguide@0.15.2

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker exec -e PYTHONPATH=/app -i flaskr-server flake8 flaskr/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        docker exec -e PYTHONPATH=/app -i flaskr-server flake8 flaskr/ --count --exit-zero --statistics

    - name: Test pytest with coverage
      run: |
        docker exec -e PYTHONPATH=/app -i flaskr-server coverage run -m pytest
        docker exec -e PYTHONPATH=/app -i flaskr-server coverage report

    - name: Check imports with isort
      run: |
        docker exec -e PYTHONPATH=/app -i flaskr-server isort flaskr/ --check-only
